rest_services:
  myonlyhomeassistant:
    fqdn: homeassistant
    base_path: /api/webhook
    port: '8123'
    ssl: False

source_streams:
- provider: twitch
  provider_settings:
    stream_name: djmissshelton
    events:
    - type: comment_activity
      settings:
        threshold_sec: 10
      actions:
      - type: sound
        settings:
          sound_file: 'sounds/alert.wav'
      - type: rest_service
        settings: 
          rest_service: myonlyhomeassistant
          method: POST
          endpoint: whon



          
